version: 2
updates:
  - package-ecosystem: pip
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
    labels: [dependencies]
    commit-message:
      prefix: deps
    groups:
      python-minor-and-patch:
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
    labels: [dependencies]
    commit-message:
      prefix: ci
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
    labels: [dependencies]
    commit-message:
      prefix: docker
