import re
from ipaddress import ip_interface

from pydantic import BaseModel, Field, field_validator

RE_IFACE_NAME = re.compile(r"^[a-zA-Z0-9_=+.-]{1,15}$")
RE_WG_KEY = re.compile(r"^[A-Za-z0-9+/]{42}[AEIMQUYcgkosw048]=?$")


class Interface(BaseModel):
    model_config = {"extra": "forbid"}

    name: str = Field(
        ...,
        description="Interface name. Any free-form string [a-zA-Z0-9_=+.-]{1,15} will work. "
        "Recommended names include 'wg0' or 'wgvpn0' or even 'wgmgmtlan0'.",
    )

    # wg(8) — Interface section fields
    private_key: str | None = Field(
        None,
        description="A base64 private key generated by wg genkey. Required.",
    )
    public_key: str | None = Field(
        None,
        description="The corresponding base64 public key, derived at runtime via wg pubkey.",
    )
    listen_port: int | None = Field(
        None,
        ge=1,
        le=65535,
        description="A 16-bit port for listening. Optional; if not specified, chosen randomly.",
    )
    fw_mark: str | None = Field(
        None,
        description="A 32-bit fwmark for outgoing packets. If set to 0 or 'off', this option is disabled. "
        "May be specified in hexadecimal by prepending '0x'. Optional.",
    )

    # wg-quick(8) — additional Interface section fields
    address: str | None = Field(
        None,
        description="A comma-separated list of IP (v4 or v6) addresses (optionally with CIDR masks) "
        "to be assigned to the interface.",
    )
    dns: str | None = Field(
        None,
        description="A comma-separated list of IP (v4 or v6) addresses to be set as the interface's DNS servers, "
        "or non-IP hostnames to be set as the interface's DNS search domains.",
    )
    mtu: int | None = Field(
        None,
        ge=1,
        le=65535,
        description="If not specified, the MTU is automatically determined from the endpoint addresses "
        "or the system default route, which is usually a sane choice. "
        "This value may be specified explicitly to override this automatic discovery.",
    )
    table: str | None = Field(
        None,
        description="Controls the routing table to which routes are added. "
        "'off' disables the creation of routes altogether, and 'auto' (the default) "
        "adds routes to the default table and enables special handling of default routes.",
    )
    pre_up: str | None = Field(
        None,
        description="Script snippet which will be executed by bash(1) before setting up the interface, "
        "most commonly used to configure custom DNS options or firewall rules. "
        "The special string '%i' is expanded to INTERFACE.",
    )
    post_up: str | None = Field(
        None,
        description="Script snippet which will be executed by bash(1) after setting up the interface, "
        "most commonly used to configure custom DNS options or firewall rules. "
        "The special string '%i' is expanded to INTERFACE.",
    )
    pre_down: str | None = Field(
        None,
        description="Script snippet which will be executed by bash(1) before tearing down the interface, "
        "most commonly used to configure custom DNS options or firewall rules. "
        "The special string '%i' is expanded to INTERFACE.",
    )
    post_down: str | None = Field(
        None,
        description="Script snippet which will be executed by bash(1) after tearing down the interface, "
        "most commonly used to configure custom DNS options or firewall rules. "
        "The special string '%i' is expanded to INTERFACE.",
    )
    save_config: bool | None = Field(
        None,
        description="If set to true, the configuration is saved from the current state of the interface "
        "upon shutdown. Any changes made to the configuration file before the interface is removed "
        "will therefore be overwritten.",
    )

    # Runtime fields (from wg show)
    num_peers: int = Field(0, description="Number of peers currently configured on this interface.")

    @field_validator("name")
    @classmethod
    def validate_name(cls, v: str) -> str:
        if not RE_IFACE_NAME.match(v):
            raise ValueError("Interface name must be 1-15 chars matching [a-zA-Z0-9_=+.-]")
        return v

    @field_validator("address")
    @classmethod
    def validate_address(cls, v: str | None) -> str | None:
        if v is not None:
            for addr in v.split(","):
                try:
                    ip_interface(addr.strip())
                except ValueError:
                    raise ValueError(f"Invalid IP address/CIDR notation: {addr.strip()}") from None
        return v

    @field_validator("private_key", "public_key")
    @classmethod
    def validate_key(cls, v: str | None) -> str | None:
        if v is not None and not RE_WG_KEY.match(v):
            raise ValueError("Invalid WireGuard key format")
        return v
