import re

from pydantic import BaseModel, Field, field_validator

RE_WG_KEY = re.compile(r"^[A-Za-z0-9+/]{42}[AEIMQUYcgkosw048]=?$")


class Peer(BaseModel):
    model_config = {"extra": "forbid"}

    # wg(8) — Peer section fields
    public_key: str | None = Field(
        None,
        description="A base64 public key calculated by wg pubkey from a private key, "
        "and usually transmitted out of band to the author of the configuration file.",
    )
    preshared_key: str | None = Field(
        None,
        description="A base64 preshared key generated by wg genpsk. Optional. "
        "This option adds an additional layer of symmetric-key cryptography to be mixed "
        "into the already existing public-key cryptography, for post-quantum resistance.",
    )
    allowed_ips: str | None = Field(
        None,
        description="A comma-separated list of IP (v4 or v6) addresses with CIDR masks from which "
        "incoming traffic for this peer is allowed and to which outgoing traffic for this peer is directed. "
        "The catch-all 0.0.0.0/0 may be specified for matching all IPv4 addresses, "
        "and ::/0 may be specified for matching all IPv6 addresses.",
    )
    endpoint: str | None = Field(
        None,
        description="An endpoint IP or hostname, followed by a colon, and then a port number. "
        "This endpoint will be updated automatically to the most recent source IP address and port "
        "of correctly authenticated packets from the peer. Optional.",
    )
    persistent_keepalive: int | None = Field(
        None,
        ge=0,
        le=65535,
        description="A seconds interval, between 1 and 65535 inclusive, of how often to send an authenticated "
        "empty packet to the peer for the purpose of keeping a stateful firewall or NAT mapping valid "
        "persistently. If set to 0 or 'off', this option is disabled. "
        "By default or when unspecified, this option is off. Most users will not need this. Optional.",
    )

    # Runtime fields (from wg show)
    latest_handshake: int | None = Field(
        None,
        description="Unix timestamp of the most recent handshake with this peer.",
    )
    transfer_rx: int | None = Field(
        None,
        description="Number of bytes received from this peer.",
    )
    transfer_tx: int | None = Field(
        None,
        description="Number of bytes transmitted to this peer.",
    )

    @field_validator("public_key", "preshared_key")
    @classmethod
    def validate_key(cls, v: str | None) -> str | None:
        if v is not None and not RE_WG_KEY.match(v):
            raise ValueError("Invalid WireGuard key format")
        return v
